### ISSUE TITLE
getIsoLabelReport error

### ISSUE THREAD

**Issue by chaesh90** [yufree/x13cms#2]
In addition to the previous issue report, currently the function getIsoLabelReport does not seem to work.
You have noted that you updated the package regarding this issue (supposing that this was based on if() error),
so I've tried your updated code and it is not fixed yet.

![image](https://github.com/yufree/x13cms/assets/145546263/9789f634-1857-43a5-af76-727afe084506)

Please take a look at the issue and fix if able to.

Thanks.

**Comment by yufree** [comment]
Same issue and it should be fixed now.

**Comment by chaesh90** [comment]
It is fixed ! Thank you so much
