### ISSUE TITLE
 printIsoListOutputs error

### ISSUE THREAD

**Issue by chaesh90** [yufree/x13cms#3]
Everything works fine thanks to your previous help.
Although, at the last step of exporting the results, this error occured
![image](https://github.com/yufree/x13cms/assets/145546263/67d06e8c-fa91-42e8-92a0-5f8b0baed53c)

resulting in this empty result file.
![image](https://github.com/yufree/x13cms/assets/145546263/d2d3769e-fca7-4ca8-95b6-3619cbf1ceef)

Can you help this?

**Comment by yufree** [comment]
I change all the && to &. It should be solved now.

**Comment by chaesh90** [comment]
After removing and reinstalling the packages from this github (remotes::intall_github('yufree/x13cms'), 
the following errer occured with getIsoLabelReport

![image](https://github.com/yufree/x13cms/assets/145546263/7cc8668f-7eff-443e-b768-99822807ecca)

**Comment by yufree** [comment]
This error might be from the data. When the `labelsMatrix` is empty, it will return this error.

**Comment by chaesh90** [comment]
I actually followed the puplication "https://www.nature.com/articles/s41596-019-0167-1#Sec19" exactly,
and my xs3 data is not empty..
What do you suggest?

**Comment by yufree** [comment]
I guess the issue is from && has short-circuit evaluation property. I tried to fix it c274f36 . Let me know if it works.
To make it clear, I am not the original author of this package.
