### ISSUE TITLE
printIsoListOutputs, filterIsoDiffReport Error

### ISSUE THREAD

**Issue by chaesh90** [yufree/x13cms#6]
Recent updates have solved many issues I was experiencing, and I finally got the result plots.

Although, the following error remains;

> printIsoListOutputs(listReport = labels, outputfile = "List.txt") 
Error in if (length(cell) > maxRows & class(cell) == "numeric") { : 
  the condition has length > 1
> printIsoListOutputs(listReport = isoDiff_Pos, outputfile = "isodiff.txt") 
Error in if (length(cell) == 1 & j == 1 & cell != -1) { : 
  the condition has length > 1
> filteredIsoDiff_Pos = filterIsoDiffReport(isoDiffReport = isoDiff_Pos, alpha = 0.05) 
Error in if (whichPeak == 1 & isoDiffReport$p_value[i][[1]] > alpha) { : 
  the condition has length > 1

**Comment by yufree** [comment]
condition length error is kinds of tricky. I just made changes to the if statement. However, I am not sure if it work.

**Comment by chaesh90** [comment]
Thank you for your immediate response. It has been fixed !

**Comment by chaesh90** [comment]
Thank you for your immediate response. It has been fixed and everything works fine!
